# -*- coding: utf-8 -*-
"""ModelFactory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3ODVtc4BboyaqH2cBmBBO7CpzwBalsv

##ModelFactory

Create models for easy lookup.

FUTURE: use metaclass programming.
"""
from keras.models import load_model
# Import local source
from model_densev1 import Model_Densev1
from model_densev11 import Model_Densev11
from model_lstmv1 import Model_LSTMv1
from model_lstmv2 import Model_LSTMv2
from model_lstmv21 import Model_LSTMv21
from model_lstmv22 import Model_LSTMv22
from model_lstmv3 import Model_LSTMv3
from model_lstmv31 import Model_LSTMv31
from model_lstmv32 import Model_LSTMv32
from model_transformerv1 import Model_Transformerv1
debug = True

DRIVE_PATH = "/data/projects/climate-data-model"

# Set the location of this script in GDrive
SCRIPT_PATH = DRIVE_PATH + "/py-src/"

class ModelFactory():
  """
  Construct a ModelFactory that provides keyword access to models for training.
  """
  def __init__(self, window_size=30, label_window=1, num_labels=1, num_epochs=300, alpha=1e-4, debug=False):

    self.debug = debug

    self.window_size = window_size
    self.label_window = label_window
    self.num_labels = num_labels
    self.num_epochs = num_epochs
    self.ALPHA = alpha
    self.total_labels = label_window * num_labels

    self.init_models()


  def __repr__(self):
    """
    Print object stats.
    """
    return '\n'.join([
         f'window_size: {self.window_size}',
         f'label_window: {self.label_window}',
         f'num_labels: {self.num_labels}',
         f'num_epochs: {self.num_epochs}',
         f'alpha: {self.ALPHA}'
    ])

  def init_models(self):
    """
    FUTURE: discover models
    """
    self.models = {}

    #TODO please use something dynamic
    model = Model_Densev1(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model

    model = Model_Densev11(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model

    model = Model_LSTMv1(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model

    model = Model_LSTMv2(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model

    model = Model_LSTMv21(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model

    model = Model_LSTMv22(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model

    model = Model_LSTMv3(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model
    model = Model_LSTMv31(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model
    model = Model_LSTMv32(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, debug=self.debug)
    self.models[model.get_name()] = model
    model = Model_Transformerv1(window_size=self.window_size,
                          label_window=self.label_window,
                          num_labels=self.num_labels,
                          num_epochs=self.num_epochs, alpha=self.ALPHA, debug=self.debug)
    self.models[model.get_name()] = model


  def get(self, model_name):
    return self.models[model_name]

  def get_saved(self, model_path):
    if (not model_path or model_path is None):
      raise AssertionError('Model path must be provided')

    # Load model to ensure we have a real model file
    model = load_model(model_path)

    # Determine what we called this model
    model_name = None
    for p in self.models.keys():
      # terminate model name with separator -
      # NOTE - highly dependent upon filename format!
      if (str(f'{p}-') in model_path):
        model_name = p
        break
    if (model_name is None):
      # Could just log and return the hdf5 model
      raise AssertionError('Model type could not be found')
    # Fetch the model and make it usable
    known_model = self.get(model_name)
    known_model.set_model(model)
    return known_model


"""---

**Unit testing**

---
"""

WG_UNIT_TEST = False

if WG_UNIT_TEST:

  print(f'-------Case 1: get single model -----------')
  mf = ModelFactory()

  model = mf.get("Densev11")
  assert(model)
  print(model)

if WG_UNIT_TEST:

  print(f'-------Case 2: get all models -----------')
  mf = ModelFactory()

  models = ["Densev1",'LSTMv1','LSTMv2','LSTMv3']

  for m in models:
    model = mf.get(m)
    assert(model)
    print(model)

if WG_UNIT_TEST:

  print(f'-------Case 3: load saved model -----------')
  mf = ModelFactory()
  # Load model
  model = mf.get_saved('/data/projects/climate-data-model/data/preds-s7/20231122-0908-Densev11-228361.hdf5')
  # Investigate
  clsnm = type(model)
  print(clsnm)
  if ('model_densev11' not in str(clsnm)):
    raise AssertionError(f'Wrong class: {clsnm}')
  model.print_summary()
